#ifndef CONFIG_H
#define CONFIG_H

#define INPUT_SENSITIVITY 15ms
#define SCAN_COLUMN_PERIOD 20ms
#define INPUT_INTERVAL 100000
#define MAX_PW_LENGTH 10
#define MAX_PW_INPUT_TIMES 4
#define PW_FALSE_SELLP_PERIOD 10000ms // 误输入等待时间

#endif